<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Harga Modal</name>
   <tag></tag>
   <elementGuidId>631971ed-91b2-4d58-bd53-a8647d2d4635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;d&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3f5eb3f-4dcc-4ff2-8a02-4d1b475602a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5b216d4-5a52-4c5c-8daa-aad4a30800bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formatNumber</value>
      <webElementGuid>0a91a345-c275-47b6-9d6b-7f58c09c7e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>d</value>
      <webElementGuid>a2432605-f67a-4385-a02a-ec53fe9e7220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-black-light sidebar-mini  pace-done&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-info&quot;]/div[@class=&quot;box-body&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;col-md-6 col-xs-12&quot;]/table[@class=&quot;table table-condensed&quot;]/tbody[1]/tr[7]/td[1]/input[@class=&quot;form-control formatNumber&quot;]</value>
      <webElementGuid>1f7198a0-9d04-4620-97ec-0f76bbd8bc7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='d']</value>
      <webElementGuid>f6c7f20f-9472-4325-a5f1-b4f354380f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/input</value>
      <webElementGuid>adeef6c3-214a-48dd-987d-cf8c704d7d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'd']</value>
      <webElementGuid>03e27aa3-21cd-41a9-b733-bf35dd51cd64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
