<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Pria Tag</name>
   <tag></tag>
   <elementGuidId>9f134c3b-38c5-4b29-9e4c-ed1cfe990eee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(16) > input[name=&quot;tag[]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='tag[]'])[16]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d286c6b-43a8-4687-b424-a8642592a5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>becefe69-0dd2-4a74-b200-999fe25f81c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pria</value>
      <webElementGuid>07bca733-fb0c-4e44-90dc-9059a074f0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tag[]</value>
      <webElementGuid>c414557a-9193-4577-bbaa-859b2843f0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-black-light sidebar-mini  pace-done&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-info&quot;]/div[@class=&quot;box-body&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;col-md-6 col-xs-12&quot;]/table[@class=&quot;table table-condensed&quot;]/tbody[1]/tr[3]/td[1]/div[@class=&quot;checkbox-scroll&quot;]/span[16]/input[1]</value>
      <webElementGuid>3a5c7280-e566-4cb6-b45d-804f3d100ec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='tag[]'])[16]</value>
      <webElementGuid>c572a78d-d193-45d4-9131-1978a1092aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[16]/input</value>
      <webElementGuid>1de6983d-1873-4f3b-a4bd-15ef77df6d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'tag[]']</value>
      <webElementGuid>6579add0-391b-4df7-8e24-819125e7c128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
