<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Data Pemilih TokoOrPerusahaan</name>
   <tag></tag>
   <elementGuidId>be4cd9f8-8de5-4f49-a51b-485d3578fffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example1']/tbody/tr/td[2]/small/i/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Toko Koko (Merangin, Jl. Sitinjau Laiuk Lauih Mandiangin)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5e70c412-8665-470c-b438-6976423f6f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Toko Koko (Merangin, Jl. Sitinjau Laiuk Lauih Mandiangin)</value>
      <webElementGuid>5326be14-f13b-4617-a67d-6a5fd9ccaf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce//administrator/detail_reseller/5</value>
      <webElementGuid>0da76362-29f6-4886-a268-63bac0d0b174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(Toko)</value>
      <webElementGuid>dd4e0626-c518-4756-b130-e5f9d67084d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/small[1]/i[1]/a[1]</value>
      <webElementGuid>bcb03ff0-d32d-4139-accd-5d0b0bb4898b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[2]/small/i/a</value>
      <webElementGuid>031012bf-8541-4006-b2e7-508bba761e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'(Toko)')]</value>
      <webElementGuid>cb3d1d73-0f7e-4ecf-9f1e-7acbc33a1114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju Koko Kids 0 - 9 tahun'])[1]/following::a[1]</value>
      <webElementGuid>714330ab-2d67-46b8-a134-4054755b2711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::a[2]</value>
      <webElementGuid>56df2081-88fc-4734-ae7c-cbac42f7608a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pcs'])[1]/preceding::a[1]</value>
      <webElementGuid>402e4ebc-c2fe-4436-86f8-b469cd335d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Y'])[1]/preceding::a[1]</value>
      <webElementGuid>5815a2be-e805-409d-b0d0-9ebaeb9b46fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(Toko)']/parent::*</value>
      <webElementGuid>cc03bf43-cff6-405a-b177-253897234eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce//administrator/detail_reseller/5')]</value>
      <webElementGuid>20b286a3-c5f6-4673-81a1-45b180416abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i/a</value>
      <webElementGuid>9dd6da46-acc1-443f-b1ec-259f27b7a9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Toko Koko (Merangin, Jl. Sitinjau Laiuk Lauih Mandiangin)' and @href = 'https://10.9.2.63/ecommerce//administrator/detail_reseller/5' and (text() = '(Toko)' or . = '(Toko)')]</value>
      <webElementGuid>04bd2e7c-2bbe-413f-b1d4-e36c23d36110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
