<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Data Nama Produk</name>
   <tag></tag>
   <elementGuidId>da3572f9-c525-449f-b012-72b6838f49c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example1']/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f92419ca-05e1-4d0c-bb5d-aad8513f5f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_BLANK</value>
      <webElementGuid>4e447dc1-eca1-4a66-8064-89c29aa95719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/produk/detail/baju-koko-kids-0--9-tahun</value>
      <webElementGuid>3044547b-b45b-4db1-ade7-9382b07e52b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baju Koko Kids 0 - 9 tahun</value>
      <webElementGuid>0d056c3f-52df-473d-b902-7954f4175f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[1]</value>
      <webElementGuid>f7476335-3a9a-418d-b3e5-d171dd2afc84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[2]/a</value>
      <webElementGuid>4286af01-dbe4-44e2-8fcd-7c73d64887f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Baju Koko Kids 0 - 9 tahun')]</value>
      <webElementGuid>e11b65a2-c9dc-4913-96f8-6865605ae14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::a[1]</value>
      <webElementGuid>7b71e22d-4822-4b71-a947-ecc3e720391a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berat'])[1]/following::a[1]</value>
      <webElementGuid>63fa0908-2004-40a3-b5b5-ddc00b32b792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Toko)'])[1]/preceding::a[1]</value>
      <webElementGuid>fbae76b8-29a0-4f8b-93ce-f4c9e57c627b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pcs'])[1]/preceding::a[2]</value>
      <webElementGuid>c457a7a5-8e20-4bd7-936a-652dd92a127b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Baju Koko Kids 0 - 9 tahun']/parent::*</value>
      <webElementGuid>63e0713c-71f8-4d81-a99a-85025a60ffd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/produk/detail/baju-koko-kids-0--9-tahun')]</value>
      <webElementGuid>68191a62-dd53-492c-815e-03976d60bbcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>86dcb217-7510-4573-97d7-6af076ad2c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/produk/detail/baju-koko-kids-0--9-tahun' and (text() = 'Baju Koko Kids 0 - 9 tahun' or . = 'Baju Koko Kids 0 - 9 tahun')]</value>
      <webElementGuid>7e033589-eedd-4bd2-bada-d570a1ec1901</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
