<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Tidak Ada</name>
   <tag></tag>
   <elementGuidId>1969baa9-ebef-4793-93d9-5b03e6c0c5ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example1']/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.dataTables_empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>72124324-ced2-4bb2-a782-9d3c2678a1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>5432bf7e-0b34-4394-8ef2-ffd092c2738e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>279d5627-8d92-4a9c-8e41-30dad3ff59c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_empty</value>
      <webElementGuid>86006c97-b259-4aab-91dd-cdabdad07008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No matching records found</value>
      <webElementGuid>b0214396-35e7-4421-a5ce-ab1a8dabacc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dataTables_empty&quot;]</value>
      <webElementGuid>731d3e21-a569-45ad-b0d0-4086e69cbaa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td</value>
      <webElementGuid>67c19dce-66cf-4503-9bde-c82cee6255fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::td[1]</value>
      <webElementGuid>936162e8-3739-4fd4-b516-599ed31c4bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berat'])[1]/following::td[1]</value>
      <webElementGuid>8c73c49e-eb09-409f-9bea-46389cc5278e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 0 to 0 of 0 entries (filtered from 29 total entries)'])[1]/preceding::td[1]</value>
      <webElementGuid>8d619d28-6f21-4ab2-ae8c-03b4fa0d56bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No matching records found']/parent::*</value>
      <webElementGuid>0b05cf3e-195d-4176-b573-bea0a6a67283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>d4252d29-4ca4-4f4a-afbd-9345c0b4d233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'No matching records found' or . = 'No matching records found')]</value>
      <webElementGuid>b8f57a1a-399b-4b95-b190-d6823a4160bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
