<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Jumlah Elektronik</name>
   <tag></tag>
   <elementGuidId>23b704f9-46ed-415d-82ae-a91bc6a4f496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[9]/div/div/div[1]/aside[3]/div/ul/li[1]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pull-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9858bcf3-4bc7-4d8b-aed0-f994d8130c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-right</value>
      <webElementGuid>172ee0f1-1d65-4d83-b2b0-827321fcf7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(5)</value>
      <webElementGuid>d53a771f-cc5e-4888-9d30-9aa41d45c6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shop-sidebar&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;ps-layout--shop&quot;]/div[@class=&quot;ps-layout__left&quot;]/aside[@class=&quot;widget widget_shop&quot;]/div[@class=&quot;widget__content&quot;]/ul[1]/li[1]/a[1]/span[@class=&quot;pull-right&quot;]</value>
      <webElementGuid>77ca03d5-cb45-47e6-9226-7421e994037c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shop-sidebar']/div/div/div/aside[3]/div/ul/li/a/span</value>
      <webElementGuid>38cdee06-536a-401d-90bf-be46c4e39b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter Merek'])[1]/following::span[1]</value>
      <webElementGuid>668e30a7-e17f-4ad3-8ba7-5629c4c5d6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(6)'])[1]/preceding::span[1]</value>
      <webElementGuid>82563d80-68e3-4724-9bb0-e945249aa8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(5)']/parent::*</value>
      <webElementGuid>62b73eb3-a32e-4105-8f82-48a1f15bddb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside[3]/div/ul/li/a/span</value>
      <webElementGuid>473b5e42-07a1-484c-b144-aa859d9f35ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '(5)' or . = '(5)')]</value>
      <webElementGuid>6907e6d9-04bc-4bc3-82d6-28e259c62588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
