<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Next Page Product</name>
   <tag></tag>
   <elementGuidId>b3fa9456-6890-440b-ad6d-3e4ac41e6110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shop-sidebar']/div/div/div[2]/div[2]/div[2]/div[3]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.pagination > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d57fd0b0-743e-4ef7-867f-aa2e28a69314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/produk/index/12?f=0&amp;s=a</value>
      <webElementGuid>f2b4f507-ef57-4991-8f32-2fc572c3cc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ci-pagination-page</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>91adb10f-286f-4858-88df-e5399d58ddd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>49734a7c-f3d6-435d-a809-45e0b87dc6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>></value>
      <webElementGuid>08c32161-37c7-41e3-ac3c-17570d79fafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shop-sidebar&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;ps-layout--shop&quot;]/div[@class=&quot;ps-layout__right&quot;]/div[@class=&quot;ps-shopping ps-tab-root&quot;]/div[@class=&quot;ps-tabs&quot;]/div[@class=&quot;ps-pagination&quot;]/ul[@class=&quot;pagination&quot;]/li[3]/a[1]</value>
      <webElementGuid>d8c04d2c-89b1-4e8e-bf70-559316a293b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shop-sidebar']/div/div/div[2]/div[2]/div[2]/div[3]/ul/li[3]/a</value>
      <webElementGuid>a19087ad-cf43-4db7-8d18-96bac1f6d9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'>')]</value>
      <webElementGuid>52e929b3-0700-46e7-9db0-18d833463fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick'])[12]/following::a[3]</value>
      <webElementGuid>0e8656ef-26d0-452b-9a7e-dc5eb31fe60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[12]/following::a[4]</value>
      <webElementGuid>786ac430-2275-4ff1-96e4-f0ea8b34c476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/preceding::a[1]</value>
      <webElementGuid>709aa8c5-ce52-4077-bfab-84f5139efda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='>']/parent::*</value>
      <webElementGuid>085c2ce8-d0be-43b5-9877-c1a9d5cd2368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://10.9.2.63/ecommerce/produk/index/12?f=0&amp;s=a')])[2]</value>
      <webElementGuid>d7d70241-45c7-4238-9f11-9847af0491fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[3]/a</value>
      <webElementGuid>8fc11b75-f51c-4ad7-a77d-a4a0a1b12985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/produk/index/12?f=0&amp;s=a' and (text() = '>' or . = '>')]</value>
      <webElementGuid>b7e1705b-01aa-47de-9f20-2db6677ea6cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
