<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>produk gak ditemukan</name>
   <tag></tag>
   <elementGuidId>62b76e06-30a2-440a-98df-657c1a94d21d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>center > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-1']/div/center/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>352096ef-fa2b-4d47-a2ec-42ccdcfe4ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oops, produk gak ditemukan</value>
      <webElementGuid>03f7d8f9-c738-4225-9a05-278c27e4fbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1&quot;)/div[@class=&quot;ps-shopping-product&quot;]/center[1]/h3[1]</value>
      <webElementGuid>ececdf65-b7a4-43f9-93e4-287f3c817177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-1']/div/center/h3</value>
      <webElementGuid>cf233008-6394-4146-ba7d-0aa0a603c60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan'])[2]/following::h3[1]</value>
      <webElementGuid>d302ff9c-5d30-487b-a153-cc1158b42e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/preceding::h3[1]</value>
      <webElementGuid>51e0d465-1920-4bba-b298-b102e3aee5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Oops, produk gak ditemukan']/parent::*</value>
      <webElementGuid>11463ae0-7e84-4e0f-aa4c-e306ada6d684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/h3</value>
      <webElementGuid>394aa7f7-af06-4f21-837a-0f21fa791f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Oops, produk gak ditemukan' or . = 'Oops, produk gak ditemukan')]</value>
      <webElementGuid>b50f25ad-9294-4beb-874f-89a8b3ca6ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
