<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Full Screen Kolom Keterangan</name>
   <tag></tag>
   <elementGuidId>04d46ad4-22e7-4bf9-8fc4-48d62a19b4e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.note-icon-arrows-alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[8]/button[1]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6dffa893-0427-4b3a-b248-e346fccc9537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-icon-arrows-alt</value>
      <webElementGuid>44ef9a98-9b62-407f-9c2a-9d66faa1436c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-black-light sidebar-mini  pace-done&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-info&quot;]/div[@class=&quot;box-body&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table table-condensed table-bordered&quot;]/tbody[1]/tr[1]/td[1]/div[@class=&quot;note-editor note-frame panel panel-default&quot;]/div[@class=&quot;note-toolbar panel-heading&quot;]/div[@class=&quot;note-btn-group btn-group note-view&quot;]/button[@class=&quot;note-btn btn btn-default btn-sm btn-fullscreen&quot;]/i[@class=&quot;note-icon-arrows-alt&quot;]</value>
      <webElementGuid>7f4f9b84-8684-431e-bc07-fa9d6ded3e59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/button/i</value>
      <webElementGuid>a7a8d960-ad44-4b46-8619-b261147fed1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
