<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Edit Voucher</name>
   <tag></tag>
   <elementGuidId>5737d172-0adb-4ea8-91ce-5c8716e08103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ps-btn.margin-btn.gray-btn.custom-btn.item_edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[12]/div/div/div[2]/div/div/table/tbody/tr[1]/td[7]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9167fe49-9fe1-4a20-a49f-3ecace24352b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>fc797eb3-2994-40b6-87b6-2a39922e3848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-btn margin-btn gray-btn custom-btn item_edit</value>
      <webElementGuid>381b07a8-da7d-4250-b2fe-64d7918142ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id_kupon</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>38c43216-5080-4135-9c9f-3a7a9698e82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kode_kupon</name>
      <type>Main</type>
      <value>Product30</value>
      <webElementGuid>050c284d-7ccf-4727-a8ee-04cc0197d5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nilai_kupon</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b301d1e2-952b-4d31-b06b-d1c5f876cca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-jumlah_kupon</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>aaf4bff2-2b16-4480-9bb6-b6cfc9430cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expire_date</name>
      <type>Main</type>
      <value>2023-11-11</value>
      <webElementGuid>9d877e77-e399-4ae7-a1b5-e178e0413576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min_order</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>605321c3-0cd5-4a7f-85b3-c91e0ab586dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>2004319d-ea9e-4e19-a93a-83af9227fa46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show_data&quot;)/tr[1]/td[7]/a[@class=&quot;ps-btn margin-btn gray-btn custom-btn item_edit&quot;]</value>
      <webElementGuid>02a4639a-43e0-4ee5-b9da-a6a60f465060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='show_data']/tr/td[7]/a</value>
      <webElementGuid>5ad86885-23bc-42e1-8021-46da119d67f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>6cb7d961-1341-4dc6-b5a2-b06801dc9c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 300'])[1]/following::a[1]</value>
      <webElementGuid>3d6c39c5-dc57-46dd-b1d3-97f57bfba9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product30'])[1]/following::a[1]</value>
      <webElementGuid>e4cd7388-8616-454c-8af1-09bdbeb8612d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus Barang ?'])[1]/preceding::a[3]</value>
      <webElementGuid>ffc1a6e7-2f2d-440b-a1c0-dfcbb536a30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>c880bcf2-a4d2-4ffc-beb4-0accb03b9d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[9]</value>
      <webElementGuid>d682a2b7-e50b-41eb-af75-88796aeb8ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>fca07e8b-3497-4632-ba9c-94b356cf729b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>15f394eb-0517-48c7-9a3a-138abaea2d4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
