<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Masa Berlaku</name>
   <tag></tag>
   <elementGuidId>0a18bb9c-2321-4c97-99b0-22859627ae8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expire_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expire_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92355a04-52e5-4e76-a45c-68ec72aaeb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expire_date</value>
      <webElementGuid>a58cae27-e3c7-4d66-ba25-359ebf32c25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd4a5046-5f82-422f-b1bd-90590973357a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expire_date</value>
      <webElementGuid>0c3c6c5e-e151-45d6-ab0c-adca5702baa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY-MM-DD HH:II:SS</value>
      <webElementGuid>d7333e91-e2e6-4221-a405-2cc4b1d7ad8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023-09-13</value>
      <webElementGuid>a8aebf35-64a6-498b-bd2c-5d106791bc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f3398e3c-389f-4b05-92b6-4fee1d3d470b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expire_date&quot;)</value>
      <webElementGuid>7a293f83-1df3-4204-a77b-b2fdf56174dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expire_date']</value>
      <webElementGuid>eeae5498-c8a0-4dd8-bd9b-e3a4e511b05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kuponProduk']/div/div/div[2]/div/div/table/thead/tr[2]/th[4]/input</value>
      <webElementGuid>e641070e-fe8a-44d4-8904-d30179feccc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/input</value>
      <webElementGuid>9e77d8d2-1566-4cc9-8408-98453caf1d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expire_date' and @type = 'text' and @name = 'expire_date' and @placeholder = 'YYYY-MM-DD HH:II:SS']</value>
      <webElementGuid>86cf6e91-a3e1-4128-a56f-ee890075f32b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
