<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Jumlah Kode kupon</name>
   <tag></tag>
   <elementGuidId>341c0b4a-f916-47bd-98aa-3e2b0f2dd5e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jumlah_kupon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jumlah_kupon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c25648f-25aa-4ebb-8829-d9671bced8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e702dff3-8126-4ad0-bfc7-308b0a0832c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jumlah_kupon</value>
      <webElementGuid>cf7f69c4-7fcd-4ede-b7ce-564654a28036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jumlah_kupon</value>
      <webElementGuid>f4299e2d-06cf-4cfb-ac47-2d0769e0c5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f107909c-6f5f-4f8e-8a30-2854f7d84370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b525d9da-1fd8-4557-baaa-694487217135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jumlah_kupon&quot;)</value>
      <webElementGuid>1e73f0a6-beeb-4958-b5b2-9c382600585e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jumlah_kupon']</value>
      <webElementGuid>1c1cd925-e4e2-406b-a005-940f5d76423b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kuponProduk']/div/div/div[2]/div/div/table/thead/tr[2]/th[3]/input</value>
      <webElementGuid>0247d1fa-ce58-4217-bed3-7eaa3f7595d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/input</value>
      <webElementGuid>534c6d8f-6e68-4492-b569-ed084c3d0118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'jumlah_kupon' and @name = 'jumlah_kupon' and @placeholder = '0']</value>
      <webElementGuid>107184ea-7318-4408-8726-26d353e5e2c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
