<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Nilai Kupon</name>
   <tag></tag>
   <elementGuidId>101b43eb-f8c5-4b06-92a7-5e918bd0e602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nilai_kupon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nilai_kupon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80a316b1-e436-48d3-9974-d9ad0134713f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nilai_kupon</value>
      <webElementGuid>a92ba04e-c9a7-4ac7-b4d0-3f77bb478861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d8d610aa-d510-41fc-a224-924f16344e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nilai_kupon</value>
      <webElementGuid>8a0007e3-2a6e-4e3a-963d-435e45d10d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formatNumber</value>
      <webElementGuid>582bd3f4-135f-4b1d-b2b0-cc7ffa3b68ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>**.***.***</value>
      <webElementGuid>73657ca0-f1be-42e1-abf0-bef48ed0e6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>500a0713-5996-4913-94f1-cf921ebec521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nilai_kupon&quot;)</value>
      <webElementGuid>c4699684-1e1c-45bf-8ec6-d80a1efef95b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nilai_kupon']</value>
      <webElementGuid>38f551bf-4499-4bd4-a51b-fbd097b4d6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kuponProduk']/div/div/div[2]/div/div/table/thead/tr[2]/th[6]/input</value>
      <webElementGuid>915528e7-f8a1-4d39-9bd7-944aa495e46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/input</value>
      <webElementGuid>9ee52a67-a4b1-403c-91ab-914ab5fad411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nilai_kupon' and @type = 'text' and @name = 'nilai_kupon' and @placeholder = '**.***.***']</value>
      <webElementGuid>f4140b89-fe1d-4759-a81b-da8c432d47c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
