<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Min Order</name>
   <tag></tag>
   <elementGuidId>17be82f3-6eb6-4596-94e8-00399d46dce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#min_order</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='min_order']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5fe2734-1492-44b4-8ca1-1a0f18eba8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5103de7b-b6ed-466d-a701-84c0477dbcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>min_order</value>
      <webElementGuid>f1259a7f-df2c-4ad5-8962-3413a45779d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>min_order</value>
      <webElementGuid>0b98b8bb-44cc-4e5a-8ab8-3cc742d1caf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a71873fe-3a05-40ee-860f-8e5e0671f4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e1c4fb78-dc42-4ae5-86d2-7467e14e4bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;min_order&quot;)</value>
      <webElementGuid>40b68b35-eacf-4c1e-a8af-ebce624262b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='min_order']</value>
      <webElementGuid>f040ca1f-5d0c-47d5-8ce7-4d8febd5c789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kuponProduk']/div/div/div[2]/div/div/table/thead/tr[2]/th[5]/input</value>
      <webElementGuid>24786f0e-3c7a-4257-b76f-189137e29db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/input</value>
      <webElementGuid>70211b57-2663-4b02-b50e-ad791b5ae7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'min_order' and @name = 'min_order']</value>
      <webElementGuid>5561d14b-2df0-4bf9-a6c8-27e8f46d82c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
