<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Kode Kupon</name>
   <tag></tag>
   <elementGuidId>6efd4ca6-6c27-4a48-9f9d-94398ebeb765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kode_kupon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kode_kupon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44927411-30af-4c7a-b46a-18745247023b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kode_kupon</value>
      <webElementGuid>3f1b4d46-4e26-4a49-84f6-f25b5fe0ebe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>nospaces(this)</value>
      <webElementGuid>08638c97-51e5-4a4b-ad5a-6554f69fc15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e583c19-e8ba-40df-8229-5abb3c432687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode_kupon</value>
      <webElementGuid>b066a005-fcb3-4bd9-90bf-e1dd3d8e2c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>XXXXXXXXX</value>
      <webElementGuid>6c7c6231-0e0c-449e-8a4a-ea3c8f0a38da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>956be55f-552e-4b27-b7d4-5212e73b7b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kode_kupon&quot;)</value>
      <webElementGuid>084669c2-ac8c-4476-9846-3510f7032a63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kode_kupon']</value>
      <webElementGuid>3a54f0f8-ac16-47f3-8dd6-d89badc6adc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kuponProduk']/div/div/div[2]/div/div/table/thead/tr[2]/th[2]/input</value>
      <webElementGuid>003b4d05-dfc6-40f1-b84c-e91994b47b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/input</value>
      <webElementGuid>e8aa6a7e-9e21-4275-8db4-bdbfc671ac37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'kode_kupon' and @type = 'text' and @name = 'kode_kupon' and @placeholder = 'XXXXXXXXX']</value>
      <webElementGuid>21dc0435-2884-4636-8b22-b2ab2973cb5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
