<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Variasi 1 Kolom 1</name>
   <tag></tag>
   <elementGuidId>84aa04a0-9650-4b24-9046-00891ea2438d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#warna_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='warna_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7d89e06-ac21-4b2c-9398-cfd388dfb13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input 1 .........</value>
      <webElementGuid>a92cf016-4da2-474d-8b07-b093159ce9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1164630c-522b-4b79-a2f5-7646f11c8037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>eec5eea2-25ca-4dfb-a2aa-93b41b6266dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>warna_1</value>
      <webElementGuid>1acf5aa7-556c-45a2-9b17-a116adc59751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>warna[]</value>
      <webElementGuid>f916d7d2-6863-452a-8a0e-849dc4f7929c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warna_1&quot;)</value>
      <webElementGuid>b6cb68ca-6172-468f-b117-a7ece0e5beb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='warna_1']</value>
      <webElementGuid>6f92d86c-deae-4edb-bad8-230676382e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_1']/input</value>
      <webElementGuid>04cf28f1-96bd-4ba0-949b-90d4b59080d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>afe76b24-aa5a-4a9a-825a-e145d513d327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Input 1 .........' and @type = 'text' and @id = 'warna_1' and @name = 'warna[]']</value>
      <webElementGuid>4ac65205-63fc-42b6-86f2-378eab5ab0ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
