<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Variasi 1 Kolom 2</name>
   <tag></tag>
   <elementGuidId>edd817ca-4b99-4ed2-a938-7777f62c67f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#warna_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='warna_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fc168fb-1edc-405f-8a60-930bd36c3d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input 2 .........</value>
      <webElementGuid>ab2b4ab0-c34e-4367-aeec-10a1e279efc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09fc6416-c77e-458e-8326-34df0e554fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>e99decf0-42d2-466a-965f-17f712666f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>warna_2</value>
      <webElementGuid>f18e3936-256e-45d0-bf0d-1317a34b6def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>warna[]</value>
      <webElementGuid>5719f962-cc42-41c7-8c94-b7eef3576ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warna_2&quot;)</value>
      <webElementGuid>7fa78efe-f050-4cf8-a3ea-c2e325b60fa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='warna_2']</value>
      <webElementGuid>12743a43-f102-41d0-837b-4fd9f3ea8134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_2']/input</value>
      <webElementGuid>229bc997-55b7-4950-999c-b7c6c747edb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>6346a9c0-6198-4355-8b6a-3353e630584a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Input 2 .........' and @type = 'text' and @id = 'warna_2' and @name = 'warna[]']</value>
      <webElementGuid>f62cfd2a-a717-44e9-b53f-fb8de39ad88a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
