<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Jumlah Variasi Warna</name>
   <tag></tag>
   <elementGuidId>42abf358-24d7-49ca-837a-cbd1f5889251</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#variasi1_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[10]/div/div/form/div/div[2]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05e848d4-06a1-4f33-affd-b34151382eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input 1 .........</value>
      <webElementGuid>199d1549-fb52-41f5-95e9-447968858bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a8c56c2-3d3e-41d3-8459-05b4e5e2c8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>84744357-bb9e-4b9f-a944-6ed1560f878e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>variasi1_1</value>
      <webElementGuid>de46a3a2-2585-4f80-b205-99a56d060083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>variasi1[]</value>
      <webElementGuid>de33e906-2541-4566-b258-50679677a6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;variasi1_1&quot;)</value>
      <webElementGuid>84f552d1-ac76-4094-b452-1eaa2fcbd57e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='variasi1_1']</value>
      <webElementGuid>83b1c343-7cb9-48ab-9e8a-1cb9f369256e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_1']/input</value>
      <webElementGuid>52f6bcd6-8de7-40bc-8483-a9ce36653a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>5bb86f0e-731a-43aa-b9bf-bb3c4bf46324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Input 1 .........' and @type = 'text' and @id = 'variasi1_1' and @name = 'variasi1[]']</value>
      <webElementGuid>1d3752d2-9134-4ccb-8dcc-2b111d856b98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
