<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih Type Wakaf</name>
   <tag></tag>
   <elementGuidId>53bac2f2-d891-470e-bafe-0ede6e2c2b9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='jenis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;jenis&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9b7efcaa-0b73-488b-8fb2-6587f578a3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-auth</value>
      <webElementGuid>dc1c0d29-534b-43cb-b489-2e9a24115e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jenis</value>
      <webElementGuid>1d363268-58d7-437d-ad7e-f8c59c8e020a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BangunanPendidikanLainnya</value>
      <webElementGuid>f2e1a9c5-001c-456d-a2cf-6a256455f208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;ps-order-tracking&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ps-section__content&quot;]/form[@class=&quot;ps-form--order-tracking&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control form-auth&quot;]</value>
      <webElementGuid>a2e8c348-10ea-42b8-9f4a-a1ae2bde2db9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='jenis']</value>
      <webElementGuid>d7c6cede-dbee-4498-8ea1-fe256eb69835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Type Wakaf *'])[1]/following::select[1]</value>
      <webElementGuid>fcbebf37-76ed-45c9-81cf-09d4ac931244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wakaf Asset Online'])[3]/following::select[1]</value>
      <webElementGuid>8cd37c08-46d8-44ab-8f7f-c30c7f5af59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perkiraan Nilai Asset *'])[1]/preceding::select[1]</value>
      <webElementGuid>65d3f847-1e07-4928-b2ad-b592c9f03791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Asset *'])[1]/preceding::select[1]</value>
      <webElementGuid>b1f97f37-8139-430a-b1dd-32c04b7bf4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/form/div/select</value>
      <webElementGuid>e5b9f35c-4d8d-4794-ad5b-c79a7f4b52d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jenis' and (text() = 'BangunanPendidikanLainnya' or . = 'BangunanPendidikanLainnya')]</value>
      <webElementGuid>a55ff579-0a94-4cdd-ab88-ca7a4b77ff2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
