<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verifikasi variasi Bertambah</name>
   <tag></tag>
   <elementGuidId>bdbd524a-c04b-4b77-9a89-1a14565d8c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='warna_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#warna_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00218432-8a6f-491b-a8dd-bc128d4e2c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input 3 .........</value>
      <webElementGuid>144b8153-ba1a-46e2-a385-fa3d03ccdc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>acb9b2a4-f453-4a10-9174-7aa1c5a3bf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>bdec7b91-244c-4a3d-90e7-e706b88a2c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>warna_3</value>
      <webElementGuid>44cf841d-b47a-4ac2-a25f-a9d2db76ff41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>warna[]</value>
      <webElementGuid>b9f679c6-9957-4ebb-bf4c-77fe375c244f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warna_3&quot;)</value>
      <webElementGuid>5a6831fd-36a4-4678-aaba-cb9ba7b777bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='warna_3']</value>
      <webElementGuid>0fdb2c85-7e6a-4347-93f4-6389490bd0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_3']/input</value>
      <webElementGuid>292ddabc-db6c-4d7f-8280-440206e8ec98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/input</value>
      <webElementGuid>da625ca3-e717-41d2-9c3b-1ba3842d1d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Input 3 .........' and @type = 'text' and @id = 'warna_3' and @name = 'warna[]']</value>
      <webElementGuid>258a26b3-3097-4d79-b4c2-2d68d6987030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
