<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verifikasi variasi Berkurang</name>
   <tag></tag>
   <elementGuidId>bd472dad-b1b4-43b4-9c5e-20c7dd5952a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='warna_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#warna_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc1f525c-2046-4547-b670-bb7b51633e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input 2 .........</value>
      <webElementGuid>76f931ea-c489-49d8-96f7-9e2710c6228b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35ee1720-01c7-4ce4-85b9-3130c42e28a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>1adca650-fd71-4afb-85b0-844c6828ca76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>warna_2</value>
      <webElementGuid>03cdd919-96e8-43d7-aa17-6afa7b5313a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>warna[]</value>
      <webElementGuid>9cf0b792-872c-4d56-9e9c-55cf7d90a50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warna_2&quot;)</value>
      <webElementGuid>fd2bb940-b88b-48a0-b95e-23d69597877d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='warna_2']</value>
      <webElementGuid>d76d0489-1676-487a-9117-e04db89aca76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_2']/input</value>
      <webElementGuid>f601cd06-c08a-46b1-9d95-58aefc67e86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>6d176932-29a0-4a0b-b826-cf40ee32954c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Input 2 .........' and @type = 'text' and @id = 'warna_2' and @name = 'warna[]']</value>
      <webElementGuid>726ec916-1cad-495f-b5f5-5223ddb652d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
